### ISSUE TITLE
Implement asymmetric neighbour detection

### ISSUE THREAD

**Issue by reisub-de** [protocollabs/dmpr-core#17]
Implement asymmetric neighbour detection using reflection, requires #16

**Comment by reisub-de** [comment]
#16 is implemented

Asymmetric neighbor detection would work like this:
Let A and B be nodes where A wants to get information about the link to B

A sends out a `reflect` request with its current sequence number:
```python
"reflect": {
    "seq": 1234,
}
```
B reflects this in its `reflected` field
```python
"reflected": {
    "A": {
        "seq": 1234,
    }
}
```
- If the reflected sequence number equals the current one of A then the last packet was transmitted successfully and we can consider the link to be symmetric and A can advertise a path to B.

- If there is no reflection for node A then the packet did not reach node B and the link is considered asymmetric and no path to B will be advertised by A.

- If the reflected sequence number is lower than the current sequence number we know there is packet loss on the way to B but the link is symmetric nevertheless. Therefore A still advertises a path to B.

**Comment by hgn** [comment]
- Is asymmetric detection an optional feature? Can we disable this feature for e.g. wired ethernet based transports?
- State asymmetric is also active after the reflected sequence number is not increased

**Comment by reisub-de** [comment]
- I thought of an configuration switch to enable/disable the feature.
It makes sense to do that on a per interface basis to disable it on reliable links.

- that's not ideal because then every packet loss would introduce route flapping. I think we should rely on the hold timer to purge that neighbor once a symmetric link has been established
